sfg:
  brewery:
    beer-inventory-service-host: "http://localhost:8082"
    inventory-user: good
    inventory-password: beer
#    request-mapping-base: /api/v1/
spring:
  jpa:
    defer-datasource-initialization: true
  cache:
    jcache:
      config: "classpath:ehcache.xml"
  datasource:
    url: "jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE"
logging:
  level:
    root: INFO
