logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
sfg:
  brewery:
    beer-inventory-service-host: "http://localhost:8082"
    inventory-user: good
    inventory-password: beer
#    request-mapping-base: /api/v1/
spring:
  cache:
    jcache:
      config: "classpath:ehcache.xml"
#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.yml
#    liquibase-schema: brewery
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
