spring:
  datasource:
    #    url: "jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE"
    url: jdbc:postgresql://localhost:5432/user?currentSchema=brewery
    username: first_test
    password: user
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 20
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
