version: 2

jobs:
  build:

    docker:
      - image: circleci/openjdk:11-browser_legacy

    working_directory: ~/repo

    environment:
      MAVEN_OPS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn integration-test
